<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Malas-MBP.attlocal.net" name="qa.vector.UspsCalculatorTest3" tests="1" failures="1" timestamp="27 Mar 2023 07:06:07 GMT" time="23.512" errors="0">
  <testcase name="uspsCalTest3" time="23.512" classname="qa.vector.UspsCalculatorTest3">
    <failure type="java.lang.AssertionError" message="Price is higher than $80 expected [true] but found [false]">
      <![CDATA[java.lang.AssertionError: Price is higher than $80 expected [true] but found [false]
	at org.testng.Assert.fail(Assert.java:94)
	at qa.vector.UspsCalculatorTest3.uspsCalTest3(UspsCalculatorTest3.java:129)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:86)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:643)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:820)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1128)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:129)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:112)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:750)
]]>
    </failure>
  </testcase> <!-- uspsCalTest3 -->
</testsuite> <!-- qa.vector.UspsCalculatorTest3 -->
